### ISSUE TITLE
Sponsor a Cohort member should show even after wallet has staked

### ISSUE THREAD

**Issue by 0x4d4n** [rite-of-moloch/rom-frontend#35]
Need the ability to sponsor other members even after your wallet's initial stake.

**Comment by personnamedmike** [comment]
Right now the component StakingFlow.jsx is getting used in various components and has a lot of props being passed down. If I add it to RiteStaked.jsx, I'm going to have to add a few more pieces of state to make sure the checkbox with `sponsor a cohort member` and the input get displayed correctly.. All of the prop drilling might get confusing.

It might be less confusing if I create a new component with some duplicate code. Is this an issue?

<img width="665" alt="Screen Shot 2022-08-30 at 6 29 36 PM" src="https://user-images.githubusercontent.com/90465420/187554900-caca8eb2-bc86-40e3-9542-c65214d07982.png">

**Comment by personnamedmike** [comment]
If wallet is not staked: 
![Screen Shot 2022-08-31 at 12 40 15 PM](https://user-images.githubusercontent.com/90465420/187732771-7a5df448-6ca5-4b31-9d59-bcdef5583571.png)

if wallet is staked:
![Screen Shot 2022-08-31 at 12 40 00 PM](https://user-images.githubusercontent.com/90465420/187732832-4dc7ece4-2999-479b-804e-fffeb7a74393.png)

**Comment by jeffreywdonahue** [comment]
looks good to me brother
