### ISSUE TITLE
Show how long before your stake could get slashed ex: "You stake will be at risk of slashing in 6 months"

### ISSUE THREAD

**Issue by BmoTheProducer** [rite-of-moloch/rom-frontend#44]
After wallet connect, we want to indicate how long the the users stake will be safe from slashing.  This data is to be pulled from the contract so the front-end UI is reusable with other deployed contracts.

**Comment by MarshBY** [comment]
Need some UX review, but the logic is implemented. As of now it looks something like this: 
![image](https://user-images.githubusercontent.com/57074511/187968756-8cc47539-8a60-489b-a3c1-c7981ad1cca9.png)

Also needs #40 to be merged as it uses Subgraph hook
