### ISSUE TITLE
Refactor code for StakingFlow

### ISSUE THREAD

**Issue by personnamedmike** [rite-of-moloch/rom-frontend#47]
Refactor code and place it into Context

**Comment by mikestarrdev** [comment]
Still working on this, but ran into some bugs. Task isn't urgent, will revisit later.

Code is here https://github.com/rite-of-moloch/rom-frontend/tree/refactor-StakingFlow

**Comment by mikestarrdev** [comment]
Closing this issue as most code is being refactored
