### ISSUE TITLE
Issue staking with large Raid balance

### ISSUE THREAD

**Issue by 0x4d4n** [rite-of-moloch/rom-frontend#50]
Tae and ApeironCreations ran into issues when attempting to stake. Both had large Raid balances. This appears to be an issue with the way the check is being performed:
`utils.formatUnits(raidBalance, "ether") >=`
and
`  const canNotStakeTooltipLabel = utils.formatUnits(raidBalance, "ether") < utils.formatUnits(minimumStake, "ether")`
 
Propose to use `BigNumber.gt()` or `BigNumber.gte()` to resolve the issue.

Additional details in ROM Discord channel.

**Comment by marcel-by** [comment]
Merged PR #51 . That should fix this. But can't test on xDai

**Comment by MantisClone** [comment]
After #51 was merged and deployed, I was able to successfully stake on xDAI.  Thus, I propose that this issue be closed.
